version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "1111:5432"
    networks:
      net:
        ipv4_address: "10.5.0.2"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      net:
        ipv4_address: "10.5.0.9"
    restart: unless-stopped

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  postgres:
  pgadmin: