version: '3.5'

services:
  postgres:
    container_name: postgres__antol_container
    image: postgres
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432"
    networks:
      net:
        ipv4_address: "10.7.0.2"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin__antol_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "4403:80"
    networks:
      net:
        ipv4_address: "10.7.0.9"
    restart: unless-stopped

  antology_back:
    container_name: antology_back
    build: ./antology
    ports:
      - "4402:4402"
    networks:
      net:
          ipv4_address: "10.7.0.4"
    restart: unless-stopped
    
  antology_front:
    container_name: antology_front
    build: ./anthology_ui
    ports:
      - "4401:4401"
    networks:
      net:
          ipv4_address: "10.7.0.5"
    restart: unless-stopped

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.0.0/16

volumes:
  postgres:
  pgadmin:
  antology_back:
  antology_front:
